// Generated by the LibSL translator.  DO NOT EDIT!
// source: *global variables*
//
package runtime;

import generated.java.util.OptionalDouble;

public class LibSLGlobals {
    public static final OptionalDouble EMPTY_OPTIONAL_DOUBLE;

    static {
        EMPTY_OPTIONAL_DOUBLE = new OptionalDouble(LibSLRuntime.Token.INSTANCE, OptionalDouble.__$lsl_States.Initialized, 0.0d, false);
    }
}
