// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package java.util;

import runtime.LibSLRuntime;

public final class ArrayList_SubList extends AbstractList implements LibSLRuntime.HasAutomaton, RandomAccess {
}
