// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package java.util;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.function.Consumer;
import java.util.function.Predicate;
import runtime.LibSLRuntime;

@LibSLRuntime.InsteadOf("java.util.ArrayList")
public final class ArrayList extends AbstractList<Object> implements LibSLRuntime.HasAutomaton, List<Object>, RandomAccess, Cloneable, Serializable {
    private ArrayListAutomaton __$lsl_automaton = null;

    @LibSLRuntime.DirectCallOnly
    public ArrayList(final ArrayListAutomaton a) {
        this.__$lsl_automaton = a;
    }

    public ArrayList(int initialCapacity) {
        this(new ArrayListAutomaton());
        this.__$lsl_automaton.ArrayList(this, initialCapacity);
    }

    public ArrayList() {
        this(new ArrayListAutomaton());
        this.__$lsl_automaton.ArrayList(this);
    }

    public ArrayList(Collection c) {
        this(new ArrayListAutomaton());
        this.__$lsl_automaton.ArrayList(this, c);
    }

    @Override
    public LibSLRuntime.Automaton __$lsl_getAutomaton() {
        return this.__$lsl_automaton;
    }

    public void trimToSize() {
        this.__$lsl_automaton.trimToSize(this);
    }

    public void ensureCapacity(int minCapacity) {
        this.__$lsl_automaton.ensureCapacity(this, minCapacity);
    }

    public int size() {
        return this.__$lsl_automaton.size(this);
    }

    public boolean isEmpty() {
        return this.__$lsl_automaton.isEmpty(this);
    }

    public boolean contains(Object o) {
        return this.__$lsl_automaton.contains(this, o);
    }

    public int indexOf(Object o) {
        return this.__$lsl_automaton.indexOf(this, o);
    }

    public int lastIndexOf(Object o) {
        return this.__$lsl_automaton.lastIndexOf(this, o);
    }

    public Object clone() {
        return this.__$lsl_automaton.clone(this);
    }

    public Object[] toArray() {
        return this.__$lsl_automaton.toArray(this);
    }

    public Object[] toArray(Object[] a) {
        return this.__$lsl_automaton.toArray(this, a);
    }

    public Object get(int index) {
        return this.__$lsl_automaton.get(this, index);
    }

    public Object set(int index, Object element) {
        return this.__$lsl_automaton.set(this, index, element);
    }

    public boolean add(Object e) {
        return this.__$lsl_automaton.add(this, e);
    }

    public void add(int index, Object element) {
        this.__$lsl_automaton.add(this, index, element);
    }

    public Object remove(int index) {
        return this.__$lsl_automaton.remove(this, index);
    }

    public boolean equals(Object other) {
        return this.__$lsl_automaton.equals(this, other);
    }

    public String toString() {
        return this.__$lsl_automaton.toString(this);
    }

    public int hashCode() {
        return this.__$lsl_automaton.hashCode(this);
    }

    public boolean remove(Object o) {
        return this.__$lsl_automaton.remove(this, o);
    }

    public void clear() {
        this.__$lsl_automaton.clear(this);
    }

    public boolean addAll(Collection c) {
        return this.__$lsl_automaton.addAll(this, c);
    }

    public boolean addAll(int index, Collection c) {
        return this.__$lsl_automaton.addAll(this, index, c);
    }

    public boolean removeAll(Collection c) {
        return this.__$lsl_automaton.removeAll(this, c);
    }

    public boolean retainAll(Collection c) {
        return this.__$lsl_automaton.retainAll(this, c);
    }

    private void writeObject(ObjectOutputStream s) throws java.io.IOException {
        this.__$lsl_automaton.writeObject(this, s);
    }

    private void readObject(ObjectInputStream s) throws java.io.IOException,
            java.lang.ClassNotFoundException {
        this.__$lsl_automaton.readObject(this, s);
    }

    public Object listIterator(int index) {
        return this.__$lsl_automaton.listIterator(this, index);
    }

    public Object listIterator() {
        return this.__$lsl_automaton.listIterator(this);
    }

    public Object iterator() {
        return this.__$lsl_automaton.iterator(this);
    }

    public Object subList(int fromIndex, int toIndex) {
        return this.__$lsl_automaton.subList(this, fromIndex, toIndex);
    }

    public void forEach(Consumer anAction) {
        this.__$lsl_automaton.forEach(this, anAction);
    }

    public Object spliterator() {
        return this.__$lsl_automaton.spliterator(this);
    }

    public boolean removeIf(Predicate filter) {
        return this.__$lsl_automaton.removeIf(this, filter);
    }

    public void replaceAll(Object op) {
        this.__$lsl_automaton.replaceAll(this, op);
    }

    public void sort(Comparator c) {
        this.__$lsl_automaton.sort(this, c);
    }
}
