// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package java.util;

import runtime.LibSLRuntime;

@LibSLRuntime.InsteadOf
public final class ArrayList_ListItr implements LibSLRuntime.HasAutomaton, Iterator {
    public boolean hasNext() {
        throw new RuntimeException();
    }

    public Object next() {
        throw new RuntimeException();
    }
}
