// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package java.util;

import java.util.stream.Stream;
import runtime.LibSLRuntime;

public final class ArrayList_Stream implements LibSLRuntime.HasAutomaton, Stream {
}
