// Generated by the LibSL translator.  DO NOT EDIT!
// source: java/util/OptionalDouble.lsl
//
package actual.java.util;

import java.util.function.DoubleConsumer;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;
import java.util.stream.DoubleStream;
import ru.spbpu.usvm.api.EngineInterface;
import runtime.LibSLGlobals;
import runtime.LibSLRuntime;

public final class OptionalDoubleAutomaton implements LibSLRuntime.Automaton {
    public __$lsl_States __$lsl_state = __$lsl_States.Allocated;

    private double value = 0.0d;

    private boolean present = false;

    @LibSLRuntime.AutomatonConstructor
    public OptionalDoubleAutomaton(__$lsl_States __$lsl_state, double value, boolean present) {
        this.__$lsl_state = __$lsl_state;
        this.value = value;
        this.present = present;
    }

    @LibSLRuntime.AutomatonConstructor
    public OptionalDoubleAutomaton() {
        this(__$lsl_States.Allocated, 0.0d, false);
    }

    public void OptionalDouble(OptionalDouble self) {
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Allocated);
        /* body */ {
            LibSLRuntime.error("Private constructor call");
        }
        this.__$lsl_state = __$lsl_States.Initialized;
    }

    public void OptionalDouble(OptionalDouble self, double x) {
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Allocated);
        /* body */ {
            LibSLRuntime.error("Private constructor call");
        }
        this.__$lsl_state = __$lsl_States.Initialized;
    }

    public static void _throwNPE() {
        /* body */ {
            throw new java.lang.NullPointerException();
        }
    }

    public static OptionalDouble empty() {
        OptionalDouble result;
        // WARNING: no state checks in static context
        /* body */ {
            result = LibSLGlobals.EMPTY_OPTIONAL_DOUBLE;
        }
        // WARNING: no state transitions in static context
        return result;
    }

    public static OptionalDouble of(double x) {
        OptionalDouble result;
        // WARNING: no state checks in static context
        /* body */ {
            result = new OptionalDouble(new OptionalDoubleAutomaton(OptionalDoubleAutomaton.__$lsl_States.Initialized, x, true));
        }
        // WARNING: no state transitions in static context
        return result;
    }

    public boolean equals(OptionalDouble self, Object other) {
        boolean result;
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            if (other == self) {
                result = true;
            } else {
                final boolean isSameType = EngineInterface.isSameType(self, other);
                if (isSameType) {
                    final double otherValue = LibSLRuntime.getAutomatonFrom(other, OptionalDoubleAutomaton.class).value;
                    final boolean otherPresent = LibSLRuntime.getAutomatonFrom(other, OptionalDoubleAutomaton.class).present;
                    if (this.present && otherPresent) {
                        result = this.value == otherValue;
                    } else {
                        result = this.present == otherPresent;
                    }
                } else {
                    result = false;
                }
            }
        }
        return result;
    }

    public double getAsDouble(OptionalDouble self) {
        double result;
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            if (!this.present) {
                throw new java.util.NoSuchElementException("No value present");
            }
            result = this.value;
        }
        return result;
    }

    public int hashCode(OptionalDouble self) {
        int result;
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            if (this.present) {
                result = EngineInterface.hashCode(this.value);
            } else {
                result = 0;
            }
        }
        return result;
    }

    public void ifPresent(OptionalDouble self, DoubleConsumer consumer) {
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            if (this.present) {
                if (consumer == null) {
                    throw new java.lang.NullPointerException();
                }
                consumer.accept(this.value);
            }
        }
    }

    public void ifPresentOrElse(OptionalDouble self, DoubleConsumer consumer,
            Runnable emptyAction) {
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            if (this.present) {
                if (consumer == null) {
                    throw new java.lang.NullPointerException();
                }
                consumer.accept(this.value);
            } else {
                if (emptyAction == null) {
                    throw new java.lang.NullPointerException();
                }
                emptyAction.run();
            }
        }
    }

    public boolean isEmpty(OptionalDouble self) {
        boolean result;
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            result = !this.present;
        }
        return result;
    }

    public boolean isPresent(OptionalDouble self) {
        boolean result;
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            result = this.present;
        }
        return result;
    }

    public double orElse(OptionalDouble self, double other) {
        double result;
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            if (this.present) {
                result = this.value;
            } else {
                result = other;
            }
        }
        return result;
    }

    public double orElseGet(OptionalDouble self, DoubleSupplier supplier) {
        double result;
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            if (supplier == null) {
                throw new java.lang.NullPointerException();
            }
            if (this.present) {
                result = this.value;
            } else {
                result = supplier.get();
            }
        }
        return result;
    }

    public double orElseThrow(OptionalDouble self) {
        double result;
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            if (!this.present) {
                throw new java.util.NoSuchElementException("No value present");
            }
            result = this.value;
        }
        return result;
    }

    public <X extends java.lang.Throwable> double orElseThrow(OptionalDouble self,
            Supplier<? extends X> exceptionSupplier) throws X {
        double result;
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            if (exceptionSupplier == null) {
                throw new java.lang.NullPointerException();
            }
            if (!this.present) {
                final Object exception = exceptionSupplier.get();
                throw ((Throwable) exception);
            } else {
                result = this.value;
            }
        }
        return result;
    }

    public DoubleStream stream(OptionalDouble self) {
        DoubleStream result;
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            LibSLRuntime.not_implemented();
        }
        return result;
    }

    public String toString(OptionalDouble self) {
        String result;
        EngineInterface.assume(this.__$lsl_state == __$lsl_States.Initialized);
        /* body */ {
            if (this.present) {
                final String valueStr = EngineInterface.toString(this.value);
                result = "OptionalDouble[" + valueStr + "]";
            } else {
                result = "OptionalDouble.empty";
            }
        }
        return result;
    }

    public enum __$lsl_States {
        Allocated,

        Initialized
    }
}
