// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package java.util;

import java.util.function.Consumer;
import runtime.LibSLRuntime;

public final class ArrayList_Spliterator implements LibSLRuntime.HasAutomaton, Spliterator {
    private ArrayList_Spliterator(ArrayList _this, int origin, int fence, int expectedModCount) {
        throw new InternalError();
    }

    public int characteristics() {
        throw new InternalError();
    }

    public boolean equals(Object obj) {
        throw new InternalError();
    }

    public long estimateSize() {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer _action) {
        throw new InternalError();
    }

    public long getExactSizeIfKnown() {
        throw new InternalError();
    }

    public int hashCode() {
        throw new InternalError();
    }

    public String toString() {
        throw new InternalError();
    }

    public boolean tryAdvance(Consumer _action) {
        throw new InternalError();
    }

    public ArrayList_Spliterator trySplit() {
        throw new InternalError();
    }
}
