// Generated by the LibSL translator.  DO NOT EDIT!
// source: java/util/OptionalDouble.lsl
//
package com.example.helloworld;

import static ru.spbpu.usvm.api.EngineInterfacing.*;

import java.util.function.DoubleConsumer;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;
import java.util.stream.DoubleStream;

public final class OptionalDouble {
    private double value = 0d;

    private boolean present = false;

    private OptionalDouble() {
        {
            throw new java.lang.RuntimeException("Private constructor call");
        }
    }

    private OptionalDouble(double x) {
        {
            throw new java.lang.RuntimeException("Private constructor call");
        }
    }

    public static OptionalDouble _makeEmpty() {
        OptionalDouble result;
        {
            result = <TODO: CallAutomatonConstructorExpression>;
        }
        return result;
    }

    public void _throwNPE() {
        {
            throw new java.lang.NullPointerException();
        }
    }

    public static OptionalDouble empty() {
        OptionalDouble result;
        {
            result = _makeEmpty();
        }
        return result;
    }

    public static OptionalDouble of(double x) {
        OptionalDouble result;
        {
            result = <TODO: CallAutomatonConstructorExpression>;
        }
        return result;
    }

    public boolean equals(Object other) {
        boolean result;
        {
            if (other == this) result = true;
            else {
                final boolean isSameType = usvmIsSameType(this, other);
                if (isSameType) {
                    final double otherValue = ((OptionalDouble) other).value;
                    final boolean otherPresent = ((OptionalDouble) other).present;
                    if (this.present && otherPresent) result = this.value == otherValue;
                    else result = this.present == otherPresent;
                }
                else result = false;
            }
        }
        return result;
    }

    public double getAsDouble() {
        double result;
        {
            if (!this.present) throw new java.util.NoSuchElementException("No value present");
            result = this.value;
        }
        return result;
    }

    public int hashCode() {
        int result;
        {
            if (this.present) result = usvmHashCode(this.value);
            else result = 0;
        }
        return result;
    }

    public void ifPresent(DoubleConsumer consumer) {
        {
            if (this.present) {
                if (consumer == null) _throwNPE();
                <TODO: call interface {consumer}>;
            }
        }
    }

    public void ifPresentOrElse(DoubleConsumer consumer, Runnable emptyAction) {
        {
            if (this.present) {
                if (consumer == null) _throwNPE();
                <TODO: call interface {consumer}>;
            }
            else {
                if (emptyAction == null) _throwNPE();
                <TODO: call interface {emptyAction}>;
            }
        }
    }

    public boolean isEmpty() {
        boolean result;
        {
            result = !this.present;
        }
        return result;
    }

    public boolean isPresent() {
        boolean result;
        {
            result = this.present;
        }
        return result;
    }

    public double orElse(double other) {
        double result;
        {
            if (this.present) result = this.value;
            else result = other;
        }
        return result;
    }

    public double orElseGet(DoubleSupplier supplier) {
        double result;
        {
            if (supplier == null) _throwNPE();
            if (this.present) result = this.value;
            else result = <TODO: call interface {supplier}>;
        }
        return result;
    }

    public double orElseThrow() {
        double result;
        {
            if (!this.present) throw new java.util.NoSuchElementException("No value present");
            result = this.value;
        }
        return result;
    }

    public double orElseThrow(Supplier exceptionSupplier) {
        double result;
        {
            if (exceptionSupplier == null) _throwNPE();
            if (!this.present) {
                final Object exception = <TODO: call interface {exceptionSupplier}>;
                throw ((Throwable) exception);
            }
            else result = this.value;
        }
        return result;
    }

    public DoubleStream stream() {
        DoubleStream result;
        {
            throw new java.lang.RuntimeException("NOT_IMPLEMENTED");
        }
        return result;
    }

    public String toString() {
        String result;
        {
            if (this.present) {
                final String valueStr = usvmToString(this.value);
                result = ("OptionalDouble[") + (valueStr) + ("]");
            }
            else result = "OptionalDouble.empty";
        }
        return result;
    }
}
