// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/stream/DoubleStream.lsl:40
//
package stub.java.util.stream;

import java.lang.Double;
import java.lang.LinkageError;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.PrimitiveIterator;
import java.util.function.Consumer;
import java.util.function.DoubleConsumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public class DoubleStreamLSLIterator implements LibSLRuntime.HasAutomaton, PrimitiveIterator.OfDouble {
    private DoubleStreamLSLIterator(Void a, Void b) {
        super();
    }

    public boolean hasNext() {
        throw new LinkageError();
    }

    public Double next() {
        throw new LinkageError();
    }

    public double nextDouble() {
        throw new LinkageError();
    }

    public void remove() {
        throw new LinkageError();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new LinkageError();
    }

    public void forEachRemaining(DoubleConsumer userAction) {
        throw new LinkageError();
    }
}
