// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.util.stream;

import java.lang.Double;
import java.lang.InternalError;
import java.util.PrimitiveIterator;
import java.util.function.Consumer;
import java.util.function.DoubleConsumer;
import runtime.LibSLRuntime;

public class DoubleStreamLSLIterator implements LibSLRuntime.HasAutomaton, PrimitiveIterator.OfDouble {
    public boolean hasNext() {
        throw new InternalError();
    }

    public Double next() {
        throw new InternalError();
    }

    public double nextDouble() {
        throw new InternalError();
    }

    public void remove() {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new InternalError();
    }

    public void forEachRemaining(DoubleConsumer userAction) {
        throw new InternalError();
    }
}
