// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/stream/DoubleStream.lsl:49
//
package stub.java.util.stream;

import java.lang.InternalError;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.Comparator;
import java.util.Spliterator;
import java.util.function.Consumer;
import java.util.function.DoubleConsumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public class DoubleStreamLSLSpliterator implements LibSLRuntime.HasAutomaton, Spliterator.OfDouble {
    private DoubleStreamLSLSpliterator(Void a, Void b) {
        super();
    }

    public int characteristics() {
        throw new InternalError();
    }

    public Spliterator.OfDouble trySplit() {
        throw new InternalError();
    }

    public void forEachRemaining(DoubleConsumer _action) {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer _action) {
        throw new InternalError();
    }

    public boolean tryAdvance(DoubleConsumer _action) {
        throw new InternalError();
    }

    public boolean tryAdvance(Consumer _action) {
        throw new InternalError();
    }

    public long estimateSize() {
        throw new InternalError();
    }

    public Comparator getComparator() {
        throw new InternalError();
    }

    public long getExactSizeIfKnown() {
        throw new InternalError();
    }

    public boolean hasCharacteristics(int _characteristics) {
        throw new InternalError();
    }
}
