// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.util.stream;

import java.lang.Integer;
import java.lang.InternalError;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.PrimitiveIterator;
import java.util.function.Consumer;
import java.util.function.IntConsumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public class IntStreamLSLIterator implements LibSLRuntime.HasAutomaton, PrimitiveIterator.OfInt {
    private IntStreamLSLIterator(Void a, Void b) {
        super();
    }

    public boolean hasNext() {
        throw new InternalError();
    }

    public Integer next() {
        throw new InternalError();
    }

    public int nextInt() {
        throw new InternalError();
    }

    public void remove() {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new InternalError();
    }

    public void forEachRemaining(IntConsumer userAction) {
        throw new InternalError();
    }
}
