// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/stream/LongStream.lsl:36
//
package stub.java.util.stream;

import java.lang.InternalError;
import java.lang.Long;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.PrimitiveIterator;
import java.util.function.Consumer;
import java.util.function.LongConsumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public class LongStreamLSLIterator implements LibSLRuntime.HasAutomaton, PrimitiveIterator.OfLong {
    private LongStreamLSLIterator(Void a, Void b) {
        super();
    }

    public boolean hasNext() {
        throw new InternalError();
    }

    public Long next() {
        throw new InternalError();
    }

    public long nextLong() {
        throw new InternalError();
    }

    public void remove() {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new InternalError();
    }

    public void forEachRemaining(LongConsumer userAction) {
        throw new InternalError();
    }
}
