// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/stream/LongStream.lsl:27
//
package stub.java.util.stream;

import java.lang.InternalError;
import java.lang.Object;
import java.lang.Runnable;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.LongSummaryStatistics;
import java.util.OptionalDouble;
import java.util.OptionalLong;
import java.util.PrimitiveIterator;
import java.util.Spliterator;
import java.util.function.BiConsumer;
import java.util.function.LongBinaryOperator;
import java.util.function.LongConsumer;
import java.util.function.LongFunction;
import java.util.function.LongPredicate;
import java.util.function.LongToDoubleFunction;
import java.util.function.LongToIntFunction;
import java.util.function.LongUnaryOperator;
import java.util.function.ObjLongConsumer;
import java.util.function.Supplier;
import java.util.stream.DoubleStream;
import java.util.stream.IntStream;
import java.util.stream.LongStream;
import java.util.stream.Stream;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public class LongStreamLSL implements LibSLRuntime.HasAutomaton, LongStream {
    private LongStreamLSL(Void a, Void b) {
        super();
    }

    public LongStream filter(LongPredicate predicate) {
        throw new InternalError();
    }

    public LongStream map(LongUnaryOperator mapper) {
        throw new InternalError();
    }

    public Stream mapToObj(LongFunction mapper) {
        throw new InternalError();
    }

    public IntStream mapToInt(LongToIntFunction mapper) {
        throw new InternalError();
    }

    public DoubleStream mapToDouble(LongToDoubleFunction mapper) {
        throw new InternalError();
    }

    public LongStream flatMap(LongFunction mapper) {
        throw new InternalError();
    }

    public LongStream sorted() {
        throw new InternalError();
    }

    public LongStream distinct() {
        throw new InternalError();
    }

    public LongStream peek(LongConsumer _action) {
        throw new InternalError();
    }

    public LongStream limit(long maxSize) {
        throw new InternalError();
    }

    public LongStream skip(long n) {
        throw new InternalError();
    }

    public void forEach(LongConsumer _action) {
        throw new InternalError();
    }

    public void forEachOrdered(LongConsumer _action) {
        throw new InternalError();
    }

    public long[] toArray() {
        throw new InternalError();
    }

    public long reduce(long identity, LongBinaryOperator accumulator) {
        throw new InternalError();
    }

    public OptionalLong reduce(LongBinaryOperator accumulator) {
        throw new InternalError();
    }

    public Object collect(Supplier supplier, ObjLongConsumer accumulator, BiConsumer combiner) {
        throw new InternalError();
    }

    public OptionalLong min() {
        throw new InternalError();
    }

    public OptionalLong max() {
        throw new InternalError();
    }

    public long count() {
        throw new InternalError();
    }

    public boolean anyMatch(LongPredicate predicate) {
        throw new InternalError();
    }

    public boolean allMatch(LongPredicate predicate) {
        throw new InternalError();
    }

    public boolean noneMatch(LongPredicate predicate) {
        throw new InternalError();
    }

    public OptionalLong findFirst() {
        throw new InternalError();
    }

    public OptionalLong findAny() {
        throw new InternalError();
    }

    public PrimitiveIterator.OfLong iterator() {
        throw new InternalError();
    }

    public Spliterator.OfLong spliterator() {
        throw new InternalError();
    }

    public boolean isParallel() {
        throw new InternalError();
    }

    public LongStream sequential() {
        throw new InternalError();
    }

    public LongStream parallel() {
        throw new InternalError();
    }

    public LongStream unordered() {
        throw new InternalError();
    }

    public LongStream onClose(Runnable closeHandler) {
        throw new InternalError();
    }

    public void close() {
        throw new InternalError();
    }

    public LongStream dropWhile(LongPredicate predicate) {
        throw new InternalError();
    }

    public LongStream takeWhile(LongPredicate predicate) {
        throw new InternalError();
    }

    public DoubleStream asDoubleStream() {
        throw new InternalError();
    }

    public long sum() {
        throw new InternalError();
    }

    public OptionalDouble average() {
        throw new InternalError();
    }

    public LongSummaryStatistics summaryStatistics() {
        throw new InternalError();
    }

    public Stream boxed() {
        throw new InternalError();
    }
}
