// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/stream/Stream.lsl:35
//
package stub.java.util.stream;

import java.lang.LinkageError;
import java.lang.Object;
import java.lang.Runnable;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.Comparator;
import java.util.Iterator;
import java.util.Optional;
import java.util.Spliterator;
import java.util.function.BiConsumer;
import java.util.function.BiFunction;
import java.util.function.BinaryOperator;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.IntFunction;
import java.util.function.Predicate;
import java.util.function.Supplier;
import java.util.function.ToDoubleFunction;
import java.util.function.ToIntFunction;
import java.util.function.ToLongFunction;
import java.util.stream.BaseStream;
import java.util.stream.Collector;
import java.util.stream.DoubleStream;
import java.util.stream.IntStream;
import java.util.stream.LongStream;
import java.util.stream.Stream;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public class StreamLSL implements LibSLRuntime.HasAutomaton, Stream {
    private StreamLSL(Void a, Void b) {
        super();
    }

    public Stream filter(Predicate predicate) {
        throw new LinkageError();
    }

    public Stream map(Function mapper) {
        throw new LinkageError();
    }

    public IntStream mapToInt(ToIntFunction mapper) {
        throw new LinkageError();
    }

    public LongStream mapToLong(ToLongFunction mapper) {
        throw new LinkageError();
    }

    public DoubleStream mapToDouble(ToDoubleFunction mapper) {
        throw new LinkageError();
    }

    public Stream flatMap(Function mapper) {
        throw new LinkageError();
    }

    public IntStream flatMapToInt(Function mapper) {
        throw new LinkageError();
    }

    public LongStream flatMapToLong(Function mapper) {
        throw new LinkageError();
    }

    public DoubleStream flatMapToDouble(Function mapper) {
        throw new LinkageError();
    }

    public Stream distinct() {
        throw new LinkageError();
    }

    public Stream sorted() {
        throw new LinkageError();
    }

    public Stream sorted(Comparator comparator) {
        throw new LinkageError();
    }

    public Stream peek(Consumer _action) {
        throw new LinkageError();
    }

    public Stream limit(long maxSize) {
        throw new LinkageError();
    }

    public Stream skip(long n) {
        throw new LinkageError();
    }

    public void forEach(Consumer _action) {
        throw new LinkageError();
    }

    public void forEachOrdered(Consumer _action) {
        throw new LinkageError();
    }

    public Object[] toArray() {
        throw new LinkageError();
    }

    public Object[] toArray(IntFunction generator) {
        throw new LinkageError();
    }

    public Object reduce(Object identity, BinaryOperator accumulator) {
        throw new LinkageError();
    }

    public Optional reduce(BinaryOperator accumulator) {
        throw new LinkageError();
    }

    public Object reduce(Object identity, BiFunction accumulator, BinaryOperator combiner) {
        throw new LinkageError();
    }

    public Object collect(Supplier supplier, BiConsumer accumulator, BiConsumer combiner) {
        throw new LinkageError();
    }

    public Object collect(Collector collector) {
        throw new LinkageError();
    }

    public Optional min(Comparator comparator) {
        throw new LinkageError();
    }

    public Optional max(Comparator comparator) {
        throw new LinkageError();
    }

    public long count() {
        throw new LinkageError();
    }

    public boolean anyMatch(Predicate predicate) {
        throw new LinkageError();
    }

    public boolean allMatch(Predicate predicate) {
        throw new LinkageError();
    }

    public boolean noneMatch(Predicate predicate) {
        throw new LinkageError();
    }

    public Optional findFirst() {
        throw new LinkageError();
    }

    public Optional findAny() {
        throw new LinkageError();
    }

    public Iterator iterator() {
        throw new LinkageError();
    }

    public Spliterator spliterator() {
        throw new LinkageError();
    }

    public boolean isParallel() {
        throw new LinkageError();
    }

    public BaseStream sequential() {
        throw new LinkageError();
    }

    public BaseStream parallel() {
        throw new LinkageError();
    }

    public BaseStream unordered() {
        throw new LinkageError();
    }

    public BaseStream onClose(Runnable arg0) {
        throw new LinkageError();
    }

    public void close() {
        throw new LinkageError();
    }

    public Stream dropWhile(Predicate predicate) {
        throw new LinkageError();
    }

    public Stream takeWhile(Predicate predicate) {
        throw new LinkageError();
    }
}
