// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.util.stream;

import java.lang.InternalError;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.Comparator;
import java.util.Spliterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public class StreamLSLSpliterator implements LibSLRuntime.HasAutomaton, Spliterator {
    private StreamLSLSpliterator(Void a, Void b) {
        super();
    }

    public int characteristics() {
        throw new InternalError();
    }

    public Spliterator trySplit() {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer _action) {
        throw new InternalError();
    }

    public boolean tryAdvance(Consumer _action) {
        throw new InternalError();
    }

    public long estimateSize() {
        throw new InternalError();
    }

    public Comparator getComparator() {
        throw new InternalError();
    }

    public long getExactSizeIfKnown() {
        throw new InternalError();
    }

    public boolean hasCharacteristics(int _characteristics) {
        throw new InternalError();
    }
}
