// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.util.stream;

import java.lang.InternalError;
import java.lang.Object;
import java.util.Iterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

public class StreamLSLIterator implements LibSLRuntime.HasAutomaton, Iterator {
    public boolean hasNext() {
        throw new InternalError();
    }

    public Object next() {
        throw new InternalError();
    }

    public void remove() {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new InternalError();
    }
}
