// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/AbstractMap.lsl:24
//
package stub.java.util;

import java.io.Serializable;
import java.lang.LinkageError;
import java.lang.Object;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.Map;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public class AbstractMap_SimpleEntry implements LibSLRuntime.HasAutomaton, Serializable, Map.Entry {
    private AbstractMap_SimpleEntry(Void a, Void b) {
        super();
    }

    public AbstractMap_SimpleEntry(Map.Entry entry) {
        throw new LinkageError();
    }

    public AbstractMap_SimpleEntry(Object key, Object value) {
        throw new LinkageError();
    }

    public boolean equals(Object other) {
        throw new LinkageError();
    }

    public Object getKey() {
        throw new LinkageError();
    }

    public Object getValue() {
        throw new LinkageError();
    }

    public int hashCode() {
        throw new LinkageError();
    }

    public Object setValue(Object value) {
        throw new LinkageError();
    }

    public String toString() {
        throw new LinkageError();
    }
}
