// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.util;

import java.lang.InternalError;
import java.lang.Void;
import java.util.ArrayList;
import java.util.Spliterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

public final class ArrayList_Spliterator implements LibSLRuntime.HasAutomaton, Spliterator {
    private ArrayList_Spliterator(Void a, Void b) {
        super();
    }

    private ArrayList_Spliterator(ArrayList _this, int origin, int fence, int expectedModCount) {
        throw new InternalError();
    }

    public int characteristics() {
        throw new InternalError();
    }

    public long estimateSize() {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer _action) {
        throw new InternalError();
    }

    public long getExactSizeIfKnown() {
        throw new InternalError();
    }

    public boolean tryAdvance(Consumer _action) {
        throw new InternalError();
    }

    public ArrayList_Spliterator trySplit() {
        throw new InternalError();
    }
}
