// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.util;

import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.RandomAccess;
import java.util.Spliterator;
import java.util.function.Consumer;
import java.util.function.IntFunction;
import java.util.function.Predicate;
import java.util.function.UnaryOperator;
import java.util.stream.Stream;
import runtime.LibSLRuntime;

public final class ArrayList_SubList extends AbstractList implements LibSLRuntime.HasAutomaton, List, RandomAccess {
    public ArrayList_SubList(ArrayList root, int fromIndex, int toIndex) {
        throw new InternalError();
    }

    private ArrayList_SubList(ArrayList_SubList parent, int fromIndex, int toIndex) {
        throw new InternalError();
    }

    public boolean add(Object e) {
        throw new InternalError();
    }

    public void add(int index, Object element) {
        throw new InternalError();
    }

    public boolean addAll(Collection c) {
        throw new InternalError();
    }

    public boolean addAll(int index, Collection c) {
        throw new InternalError();
    }

    public void clear() {
        throw new InternalError();
    }

    public boolean contains(Object o) {
        throw new InternalError();
    }

    public boolean containsAll(Collection c) {
        throw new InternalError();
    }

    public boolean equals(Object o) {
        throw new InternalError();
    }

    public void forEach(Consumer _action) {
        throw new InternalError();
    }

    public Object get(int index) {
        throw new InternalError();
    }

    public int hashCode() {
        throw new InternalError();
    }

    public int indexOf(Object o) {
        throw new InternalError();
    }

    public boolean isEmpty() {
        throw new InternalError();
    }

    public Iterator iterator() {
        throw new InternalError();
    }

    public int lastIndexOf(Object o) {
        throw new InternalError();
    }

    public ListIterator listIterator() {
        throw new InternalError();
    }

    public ListIterator listIterator(int index) {
        throw new InternalError();
    }

    public Stream parallelStream() {
        throw new InternalError();
    }

    public boolean remove(Object o) {
        throw new InternalError();
    }

    public Object remove(int index) {
        throw new InternalError();
    }

    public boolean removeAll(Collection c) {
        throw new InternalError();
    }

    public boolean removeIf(Predicate filter) {
        throw new InternalError();
    }

    public void replaceAll(UnaryOperator operator) {
        throw new InternalError();
    }

    public boolean retainAll(Collection c) {
        throw new InternalError();
    }

    public Object set(int index, Object element) {
        throw new InternalError();
    }

    public int size() {
        throw new InternalError();
    }

    public void sort(Comparator c) {
        throw new InternalError();
    }

    public Spliterator spliterator() {
        throw new InternalError();
    }

    public Stream stream() {
        throw new InternalError();
    }

    public List subList(int fromIndex, int toIndex) {
        throw new InternalError();
    }

    public Object[] toArray() {
        throw new InternalError();
    }

    public Object[] toArray(IntFunction generator) {
        throw new InternalError();
    }

    public Object[] toArray(Object[] a) {
        throw new InternalError();
    }

    public String toString() {
        throw new InternalError();
    }
}
