// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.util;

import java.util.ListIterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

public final class ArrayList_ListItr implements LibSLRuntime.HasAutomaton, ListIterator {
    public boolean hasPrevious() {
        throw new InternalError();
    }

    public int nextIndex() {
        throw new InternalError();
    }

    public int previousIndex() {
        throw new InternalError();
    }

    public boolean hasNext() {
        throw new InternalError();
    }

    public Object next() {
        throw new InternalError();
    }

    public Object previous() {
        throw new InternalError();
    }

    public void remove() {
        throw new InternalError();
    }

    public void set(Object e) {
        throw new InternalError();
    }

    public void add(Object e) {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new InternalError();
    }
}
