// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.util;

import java.lang.InternalError;
import java.util.Spliterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

public final class ArrayList_SubList$Spliterator implements LibSLRuntime.HasAutomaton, Spliterator {
    public int characteristics() {
        throw new InternalError();
    }

    public long estimateSize() {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer _action) {
        throw new InternalError();
    }

    public long getExactSizeIfKnown() {
        throw new InternalError();
    }

    public boolean tryAdvance(Consumer _action) {
        throw new InternalError();
    }

    public ArrayList_SubList$Spliterator trySplit() {
        throw new InternalError();
    }
}
