// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.util;

import java.util.HashMap;
import java.util.Iterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

public final class HashSet_KeyIterator implements LibSLRuntime.HasAutomaton, Iterator {
    private HashSet_KeyIterator(HashMap source) {
        throw new InternalError();
    }

    public boolean hasNext() {
        throw new InternalError();
    }

    public final Object next() {
        throw new InternalError();
    }

    public void remove() {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new InternalError();
    }
}
