// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/HashMap.lsl:46
//
package stub.java.util;

import java.lang.LinkageError;
import java.lang.Object;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.HashMap;
import java.util.Iterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public class HashMap_ValueIterator implements LibSLRuntime.HasAutomaton, Iterator {
    private HashMap_ValueIterator(Void a, Void b) {
        super();
    }

    private HashMap_ValueIterator(HashMap _this) {
        throw new LinkageError();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new LinkageError();
    }

    public final boolean hasNext() {
        throw new LinkageError();
    }

    public final Object next() {
        throw new LinkageError();
    }

    public final void remove() {
        throw new LinkageError();
    }
}
