// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/HashMap.lsl:100
//
package stub.java.util;

import java.lang.LinkageError;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.Iterator;
import java.util.Map;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public final class HashMap_EntryIterator implements LibSLRuntime.HasAutomaton, Iterator {
    private HashMap_EntryIterator(Void a, Void b) {
        super();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new LinkageError();
    }

    public final boolean hasNext() {
        throw new LinkageError();
    }

    public final Map.Entry next() {
        throw new LinkageError();
    }

    public final void remove() {
        throw new LinkageError();
    }
}
