// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/HashMap.lsl:54
//
package stub.java.util;

import java.lang.LinkageError;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.Spliterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public final class HashMap_ValueSpliterator implements LibSLRuntime.HasAutomaton, Spliterator {
    private HashMap_ValueSpliterator(Void a, Void b) {
        super();
    }

    public int characteristics() {
        throw new LinkageError();
    }

    public final long estimateSize() {
        throw new LinkageError();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new LinkageError();
    }

    public long getExactSizeIfKnown() {
        throw new LinkageError();
    }

    public boolean tryAdvance(Consumer userAction) {
        throw new LinkageError();
    }

    public Spliterator trySplit() {
        throw new LinkageError();
    }
}
