// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.util;

import java.lang.InternalError;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.HashMap;
import java.util.Spliterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public final class LinkedHashSet_KeySpliterator implements LibSLRuntime.HasAutomaton, Spliterator {
    private LinkedHashSet_KeySpliterator(Void a, Void b) {
        super();
    }

    private LinkedHashSet_KeySpliterator(HashMap source, int origin, int fence, int est,
            int expectedModCount) {
        throw new InternalError();
    }

    public long estimateSize() {
        throw new InternalError();
    }

    public int characteristics() {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new InternalError();
    }

    public boolean tryAdvance(Consumer userAction) {
        throw new InternalError();
    }

    public Spliterator trySplit() {
        throw new InternalError();
    }
}
