// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.util;

import java.lang.InternalError;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.LinkedList;
import java.util.Spliterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public final class LinkedList_Spliterator implements LibSLRuntime.HasAutomaton, Spliterator {
    private LinkedList_Spliterator(Void a, Void b) {
        super();
    }

    private LinkedList_Spliterator(LinkedList _this, int origin, int fence, int expectedModCount) {
        throw new InternalError();
    }

    public int characteristics() {
        throw new InternalError();
    }

    public long estimateSize() {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer _action) {
        throw new InternalError();
    }

    public long getExactSizeIfKnown() {
        throw new InternalError();
    }

    public boolean tryAdvance(Consumer _action) {
        throw new InternalError();
    }

    public Spliterator trySplit() {
        throw new InternalError();
    }
}
