// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/LinkedList.lsl:35
//
package stub.java.util;

import java.lang.LinkageError;
import java.lang.Object;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.ListIterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public final class LinkedList_ListItr implements LibSLRuntime.HasAutomaton, ListIterator {
    private LinkedList_ListItr(Void a, Void b) {
        super();
    }

    public boolean hasPrevious() {
        throw new LinkageError();
    }

    public int nextIndex() {
        throw new LinkageError();
    }

    public int previousIndex() {
        throw new LinkageError();
    }

    public boolean hasNext() {
        throw new LinkageError();
    }

    public Object next() {
        throw new LinkageError();
    }

    public Object previous() {
        throw new LinkageError();
    }

    public void remove() {
        throw new LinkageError();
    }

    public void set(Object e) {
        throw new LinkageError();
    }

    public void add(Object e) {
        throw new LinkageError();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new LinkageError();
    }
}
