// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/LinkedHashSet.lsl:39
//
package stub.java.util;

import java.lang.LinkageError;
import java.lang.Object;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.HashMap;
import java.util.Iterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public final class LinkedHashSet_KeyIterator implements LibSLRuntime.HasAutomaton, Iterator {
    private LinkedHashSet_KeyIterator(Void a, Void b) {
        super();
    }

    private LinkedHashSet_KeyIterator(HashMap source) {
        throw new LinkageError();
    }

    public boolean hasNext() {
        throw new LinkageError();
    }

    public final Object next() {
        throw new LinkageError();
    }

    public void remove() {
        throw new LinkageError();
    }

    public void forEachRemaining(Consumer userAction) {
        throw new LinkageError();
    }
}
