// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.util;

import java.lang.InternalError;
import java.lang.Void;
import java.util.Comparator;
import java.util.Spliterator;
import java.util.function.Consumer;
import java.util.function.LongConsumer;
import runtime.LibSLRuntime;

public class LongStreamLSLSpliterator implements LibSLRuntime.HasAutomaton, Spliterator.OfLong {
    private LongStreamLSLSpliterator(Void a, Void b) {
        super();
    }

    public int characteristics() {
        throw new InternalError();
    }

    public Spliterator.OfLong trySplit() {
        throw new InternalError();
    }

    public void forEachRemaining(LongConsumer _action) {
        throw new InternalError();
    }

    public void forEachRemaining(Consumer _action) {
        throw new InternalError();
    }

    public boolean tryAdvance(LongConsumer _action) {
        throw new InternalError();
    }

    public boolean tryAdvance(Consumer _action) {
        throw new InternalError();
    }

    public long estimateSize() {
        throw new InternalError();
    }

    public Comparator getComparator() {
        throw new InternalError();
    }

    public long getExactSizeIfKnown() {
        throw new InternalError();
    }

    public boolean hasCharacteristics(int _characteristics) {
        throw new InternalError();
    }
}
