// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/Spliterators.lsl:62
//
package stub.java.util;

import java.lang.LinkageError;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.Comparator;
import java.util.Spliterator;
import java.util.function.Consumer;
import java.util.function.IntConsumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public final class Spliterators_IntArraySpliterator implements LibSLRuntime.HasAutomaton, Spliterator.OfInt {
    private Spliterators_IntArraySpliterator(Void a, Void b) {
        super();
    }

    public Spliterators_IntArraySpliterator(int[] arr, int additionalCharacteristics) {
        throw new LinkageError();
    }

    public Spliterators_IntArraySpliterator(int[] arr, int origin, int pFence,
            int additionalCharacteristics) {
        throw new LinkageError();
    }

    public int characteristics() {
        throw new LinkageError();
    }

    public long estimateSize() {
        throw new LinkageError();
    }

    public void forEachRemaining(Consumer _action) {
        throw new LinkageError();
    }

    public void forEachRemaining(IntConsumer _action) {
        throw new LinkageError();
    }

    public Comparator getComparator() {
        throw new LinkageError();
    }

    public long getExactSizeIfKnown() {
        throw new LinkageError();
    }

    public boolean hasCharacteristics(int _characteristics) {
        throw new LinkageError();
    }

    public boolean tryAdvance(IntConsumer _action) {
        throw new LinkageError();
    }

    public boolean tryAdvance(Consumer _action) {
        throw new LinkageError();
    }

    public Spliterator.OfInt trySplit() {
        throw new LinkageError();
    }
}
