// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - java/util/Spliterators.lsl:45
//
package stub.java.util;

import java.lang.LinkageError;
import java.lang.Object;
import java.lang.SuppressWarnings;
import java.lang.Void;
import java.util.Comparator;
import java.util.Spliterator;
import java.util.function.Consumer;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public final class Spliterators_ArraySpliterator implements LibSLRuntime.HasAutomaton, Spliterator {
    private Spliterators_ArraySpliterator(Void a, Void b) {
        super();
    }

    public Spliterators_ArraySpliterator(Object[] arr, int additionalCharacteristics) {
        throw new LinkageError();
    }

    public Spliterators_ArraySpliterator(Object[] arr, int origin, int pFence,
            int additionalCharacteristics) {
        throw new LinkageError();
    }

    public int characteristics() {
        throw new LinkageError();
    }

    public long estimateSize() {
        throw new LinkageError();
    }

    public void forEachRemaining(Consumer _action) {
        throw new LinkageError();
    }

    public Comparator getComparator() {
        throw new LinkageError();
    }

    public long getExactSizeIfKnown() {
        throw new LinkageError();
    }

    public boolean hasCharacteristics(int _characteristics) {
        throw new LinkageError();
    }

    public boolean tryAdvance(Consumer _action) {
        throw new LinkageError();
    }

    public Spliterator trySplit() {
        throw new LinkageError();
    }
}
