// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.io;

import java.io.InputStream;
import java.io.OutputStream;
import java.lang.InternalError;
import java.lang.SuppressWarnings;
import java.lang.Void;
import runtime.LibSLRuntime;

@SuppressWarnings({"all", "unchecked"})
public final class InputStream$Void extends InputStream implements LibSLRuntime.HasAutomaton {
    private InputStream$Void(Void a, Void b) {
        super();
    }

    public int available() throws java.io.IOException {
        throw new InternalError();
    }

    public void close() throws java.io.IOException {
        throw new InternalError();
    }

    public synchronized void mark(int readlimit) {
        throw new InternalError();
    }

    public boolean markSupported() {
        throw new InternalError();
    }

    public int read() throws java.io.IOException {
        throw new InternalError();
    }

    public int read(byte[] b) throws java.io.IOException {
        throw new InternalError();
    }

    public int read(byte[] b, int off, int len) throws java.io.IOException {
        throw new InternalError();
    }

    public byte[] readAllBytes() throws java.io.IOException {
        throw new InternalError();
    }

    public int readNBytes(byte[] b, int off, int len) throws java.io.IOException {
        throw new InternalError();
    }

    public byte[] readNBytes(int len) throws java.io.IOException {
        throw new InternalError();
    }

    public synchronized void reset() throws java.io.IOException {
        throw new InternalError();
    }

    public long skip(long n) throws java.io.IOException {
        throw new InternalError();
    }

    public long transferTo(OutputStream out) throws java.io.IOException {
        throw new InternalError();
    }
}
