// Generated by the LibSL translator.  DO NOT EDIT!
// source: ?
//
package stub.java.io;

import java.io.OutputStream;
import java.lang.InternalError;
import java.lang.Void;
import runtime.LibSLRuntime;

public final class OutputStream$Void extends OutputStream implements LibSLRuntime.HasAutomaton {
    private OutputStream$Void(Void a, Void b) {
        super();
    }

    public void close() {
        throw new InternalError();
    }

    public void flush() throws java.io.IOException {
        throw new InternalError();
    }

    public void write(byte[] b) throws java.io.IOException {
        throw new InternalError();
    }

    public void write(byte[] b, int off, int len) throws java.io.IOException {
        throw new InternalError();
    }

    public void write(int b) throws java.io.IOException {
        throw new InternalError();
    }
}
